@startuml "Логические компоненты системы"

package "Система" {
    [Пользовательский интерфейс(API)] --> [Бизнес-логика]
    [Бизнес-логика] --> [Система лояльности]
    [Система лояльности] --> [База данных]
}

[Бизнес-логика] --> [Внешняя система]
[Интернет-магазин] --> [Бизнес-логика]

@enduml