@startuml "Последовательность Накопительная система лояльности «Гофермарт»"
actor User as U
participant "Гофермарт" as G
participant "Система лояльности" as S


U -> G: Покупка товаров
activate G
G -> U: Номер заказа
deactivate G


U -> S: Регистрация
activate S
S -> U: Подтверждение регистрации
deactivate S


U -> S: Передача номера заказа
activate S
S -> S: Сверка номера заказа
alt Положительный расчёт
    S -> S: Начисление баллов
    S -> U: Уведомление о начислении баллов
else Отрицательный расчёт
    S -> U: Уведомление о невозможности начисления баллов
end

U -> S: Использование баллов для оплаты
activate S
S -> S: Проверка баланса
alt Достаточно баллов
    S -> U: Подтверждение оплаты баллами
else Недостаточно баллов
    S -> U: Уведомление о недостаточном балансе
end
deactivate S

@enduml